<div class="full">
	<div class="isi-full">
	<div class="judul-full">
	PERATURAN DI PERPUSTAKAAN ATHENA
	</div>
		<ol class="peraturan">
			<li>UNTUK DAPAT LOGIN, HARAP MUNGHUBUNGI PETUGAS YANG SEDANG BERJAGA UNTUK MENDAPATKAN PASSWORD.</li>
			<li>UNTUK DAPAT MEMINJAM DAN MEMBAWA PULANG, ANDA HARUS MENJADI ANGGOTA DENGAN MENGHUBUNGI PETUGAS PERPUSTAKAAN.</li>
			<li>BIAYA PENDAFTARAN SEBESAR Rp. 10.000,- DAN DIBAYARKAN SAAT PENDAFTARAN.</li>
			<li>SAAT MEMINJAM,SELALU BAWA KARTU PERPUSTAKAAN ANDA.</li>
			<li>HARAP MENGEMBALIKAN BUKU DI RAK YANG BENAR AGAR MEMUDAHKAN MENCARI BUKU.</li>
			<li>JIKA ANDA TELAT MENGEMBALIKAN,MAKA PER HARI ANDA AKAN DIKENAKAN BIAYA RP 500,- PER BUKU.</li>
			<li>E-BOOK ADALAH FREEWARE,JADI SILAHKAN DOWNLOAD SECARA GRATIS DAN BACA DI SMARTPHONE ATAU KOMPUTER ANDA</li>
		</ol>
	</div>
	</div>
	<center><object data="images/footer.swf" width="800" height="200"></object></center>